# Generated by Django 2.0 on 2019-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LCLid', models.CharField(max_length=20)),
                ('stdorToU', models.CharField(max_length=20)),
                ('Acorn', models.CharField(max_length=20)),
                ('Acorn_grouped', models.CharField(max_length=20)),
                ('file', models.CharField(max_length=20)),
            ],
        ),
    ]
